### ISSUE TITLE
Implementation as Scikit Learn Method

### ISSUE THREAD

**Issue by felipeffm** [Behrouz-Babaki/MinSizeKmeans#13]
Hi,
I implemented the algorithm as a scikit classifier module so that is possible to place in scikit pipeline. Should I make a commit?

**Comment by Behrouz-Babaki** [comment]
Hi

Thanks a lot for the proposal.
In the spirit of keeping the code as simple as possible, I have tried to avoid adding such functionalities. 

If a user absolutely needs methods similar to those offered by sklearn, I think they can easily wrap a function around the existing ones.
