### ISSUE TITLE
Run on CSV with multiple columns

### ISSUE THREAD

**Issue by EricRoche** [Behrouz-Babaki/MinSizeKmeans#4]
Hi,

How should I run on a CSV with multiple columns?

ex: I want to cluster data from a csv that contains:
1. Column One - Latitude
2. Column Two - Longitude

Thanks!

**Comment by EricRoche** [comment]
It seems like like concatinating the two fields into a single field with a blank space seperating latitude and longitude works. However, wanted to double check that my interpretation is correct.

**Comment by Behrouz-Babaki** [comment]
@EricRoche You are right. In the input file, each point appears as a list of coordinates that are separated by whitespace (space, tab, etc). See the [iris dataset](https://github.com/Behrouz-Babaki/MinSizeKmeans/blob/bb7fe57f97fcaf11647fe85e4fce3a9e9e075095/data/iris.data) as an example.

**Comment by EricRoche** [comment]
This worked perfectly for me. Thanks!
