### ISSUE TITLE
Scalability to 1.3 million 256-dimensional

### ISSUE THREAD

**Issue by creiser** [Behrouz-Babaki/MinSizeKmeans#5]
I have a dataset consisting of 1.3 million 256-dimensional vectors. Should I give it a try or is it a total waste of time?

**Comment by Behrouz-Babaki** [comment]
The bottleneck in *MinSizeKmeans* is solving a linear program at each iteration of the *KMeans* algorithm. The total number of variables in this LP is equal to the number of instances times the number of clusters. There might be way too many variables in your problem. 

The mentioned linear program is meant to solve a network flow problem. However, there are other ways for solving these problems. [Here](https://adared.ch/constrained-k-means-implementation-in-python/) you can find another implementation. The algorithm used in this implementation can only solve flow problems with integer values. Hence the floating point numbers have to first be scaled to a close integer number. This might or might not be a major concern for you.
