### ISSUE TITLE
Write best cluster algorithm

### ISSUE THREAD

**Issue by lukasgartmair** [Behrouz-Babaki/MinSizeKmeans#8]
`    best = None
    best_clusters = None
    for i in range(args.NUM_ITER):
        clusters, centers = minsize_kmeans(data, args.k, 
                                           args.min_size, args.max_size)
        if clusters:
            quality = compute_quality(data, clusters)
            if not best or (quality < best):
                best = quality
                best_clusters = clusters
    if best:
        if args.OUTFILE:
            with open(args.OUTFILE, 'w') as f:
                print('\n'.join(str(i) for i in clusters), file=f)
        else:
            print('cluster assignments:')
            for i in range(len(clusters)):
                print('%d: %d'%(i, clusters[i]))
        print('sum of squared distances: %.4f'%(best))
    else:
print('no clustering found')`

Just a question, maybe I am wrong, but if you found a best cluster configuration, should not the variable best_clusters written to the file instead of the last cluster configuration? Regards Lukas

**Comment by Behrouz-Babaki** [comment]
Hi. Your point is valid. The reason for the current implementation is that this best suited my own needs. In the interest of keeping things simple, I did not add options for every possible use case, trusting that this will be easy for the users to modify.
