### ISSUE TITLE
Cannot implement in Python 3.5 Conda Environment

### ISSUE THREAD

**Issue by djpecot** [Behrouz-Babaki/MinSizeKmeans#9]
Hi all,

I cloned this repo and made a fresh install of Anaconda (ver. 4.7.12), created a new environment using the following command:

`conda create -n py35 python=3.5 anaconda`

Followed by activating py35

`conda activate py35`

After making this environment, proceeded to run the code, throwing the following error:

`Requested Python version (3.5) is not installed`

Even though I confirm that the python version is correct:

`python --version`
`Python 3.5.5`

It won't run. Any advice would be great. I am currently running on Windows 7, and this is my full conda info list:

`active environment : py35`
`active env location : C:\Users\Doug\Anaconda3\envs\py35`
`shell level : 2`
`user config file : C:\Users\Doug\.condarc`
`populated config files : C:\Users\Doug\.condarc`
`conda version : 4.7.12`
`conda-build version : 3.18.9`
`python version : 3.7.4.final.0`
`virtual packages :`
`base environment : C:\Users\Doug\Anaconda3  (writable)`
`channel URLs : https://conda.anaconda.org/conda-forge/win-64`
`https://conda.anaconda.org/conda-forge/noarch`
`https://repo.anaconda.com/pkgs/main/win-64`
`https://repo.anaconda.com/pkgs/main/noarch`
`https://repo.anaconda.com/pkgs/r/win-64`
`https://repo.anaconda.com/pkgs/r/noarch`
`https://repo.anaconda.com/pkgs/msys2/win-64`
`https://repo.anaconda.com/pkgs/msys2/noarch`
`package cache : C:\Users\Doug\Anaconda3\pkgs`
`C:\Users\Doug\.conda\pkgs`
`C:\Users\Doug\AppData\Local\conda\conda\pkgs`
`envs directories : C:\Users\Doug\Anaconda3\envs`
`C:\Users\Doug\.conda\envs`
`C:\Users\Doug\AppData\Local\conda\conda\envs`
`platform : win-64`
`user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Windows/7 W`
`ows/6.1.7601`
`administrator : False`
`netrc file : None`
`offline mode : False`

**Comment by Behrouz-Babaki** [comment]
One possible thing to try is to change the following lines in each `.py` file:
```
#!/usr/bin/env python3.5
```
to this:
```
#!/usr/bin/env python3
```
